import { _electron as electron } from '/home/frappeuser/tamken3-audit/node_modules/playwright/index.mjs'
const app = await electron.launch({ executablePath: '/root/meena-time/node_modules/electron/dist/electron', args: ['.', '--no-sandbox'], cwd: '/root/meena-time' })
const p = await app.firstWindow()
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (m.type() === 'error') errs.push(m.text()) })
await p.waitForSelector('text=شاشة الدخول', { timeout: 20000 })
await p.getByText('موافق').click(); await p.waitForTimeout(800)
console.log('home tiles:', await p.locator('.tile').count(), '| caption:', await p.locator('#caption-text').textContent())
await p.getByRole('button', { name: 'البيانات الأساسية', exact: true }).click()
await p.locator('.menu.open .drop button', { hasText: 'مواعيد العمل' }).click(); await p.waitForTimeout(300)
const w = p.locator('.win').first(); await w.locator('tbody tr').last().locator('[data-f=name_ar]').fill('دوام إلكترون')
await w.getByRole('button', { name: 'حفظ' }).click(); await p.waitForTimeout(500)
const userData = await app.evaluate(({ app }) => app.getPath('userData'))
const fs = await import('fs'); console.log('db files:', fs.readdirSync(userData).filter(f => f.endsWith('.sqlite')), '| backups dir:', fs.existsSync(userData + '/backups'))
const lic = await p.evaluate(() => window.bridge.licenceStatus()); console.log('request code:', lic.requestCode, 'registered:', lic.ok)
const dev = await p.evaluate(() => window.bridge.readDevice({ ip: '127.0.0.1', port: 4370 })); console.log('device (none present):', dev.ok, dev.error?.slice(0, 40))
console.log('errors:', errs)
await app.close()
console.log('USERDATA', userData)
